### ISSUE TITLE
タグにカテゴリを付与して選択しやすくする

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#105]
スポーツ: サッカー、野球、バスケ
テクノロジー: プログラミング、エンジニアリング

みたいなイメージ

**Comment by wkmkymt** [comment]
あくまで「スポーツ」「テクノロジー」はカテゴリで、実際に選択するのは「野球」「バスケ」「プログラミング」っていうタグって認識でOK？

「スポーツ」のみを選択っていうのは不可？

**Comment by e45395** [comment]
その認識でOK。
スポーツのみを選択は不可でも良いと思われる。

仕様が固まらないので優先度下げます。
