### ISSUE TITLE
チェックイン処理時に予期せぬユーザがチェックインしてしまう

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#107]
/checkin/[used_id]でチェックインをミスした後に他ユーザをチェックインするとadminやstaffアカウントもチェックインされてしまう。

1. 手打ちで/checkin/[used_id]=>既にチェックイン済みor存在しないuser_idなどでチェックイン失敗
2. 手打ちで/checkin/[another_used_id] =>チェックイン成功するが、adminやstaffアカウントもチェックインされてしまう

**Comment by e45395** [comment]
再現方法に懐疑あり

**Comment by e45395** [comment]
どうやら手打ちで「/checkin/[user_id]」を打ったあとにリロードせずとも、「/checkin/[user_id]」が反映される場合がある(?)

ブラウザの先読みアクセスなどが起因？

**Comment by e45395** [comment]
よく分からないので、staffユーザのプロフ画面にも手動チェックアウトボタンを設置。
運用中に事象が発生したら手動チェックアウトで対応

**Comment by wkmkymt** [comment]
なんか再現できなくなっちゃったしとりあえず保留に・・・
(Closeせずに残しとく)
