### ISSUE TITLE
staffロールのアカウントをguestロールのようにも使えるようにする

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#139]
スタッフがstaffロールのアカウントをguestロールのようにプライベートでも使えるようにする。
基本的には現行のまま流用できそう。

プロフ画面に勤務ボタン(linkは/checkin/[user_id]?workingstaff=trueみたいな感じ？)を設置し、勤務ボタン経由でcheckinすると、プロフ一覧の名前が「本日のスタッフ」に変わり、K-Displayでの表示も名前の上に「本日のスタッフ」と表示されるようにする。
退勤ボタンも用意する。(こちらは普通にcheckoutで良さそう？

プライベートでの利用は通常通りQRコードを介して行う。

**Comment by wkmkymt** [comment]
スタッフアカウントって店舗共有の端末のみで運用する訳ではないの？ (チェックイン処理とか)

**Comment by e45395** [comment]
多分店舗共有端末がない気がするから、スタッフ個人のスマホでやらなアカン気がしてる

**Comment by wkmkymt** [comment]
oh...

**Comment by e45395** [comment]
これから1,2店舗だけじゃなくどんどん増えていくなら尚更そういう店舗も出てきそう()

**Comment by e45395** [comment]
用意してもらえるなら、用意させるのも1つ手ではあるが、微妙に辛そう(?)
