### ISSUE TITLE
adminアカウントのメールアドレス

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#140]
実運用を考えるとしっかりと用意すべき？
(セキュリティ的にメール送信用のアドレスとは分けた方が良さそう)

仮アドレスのままでも当分は大丈夫だと思われるが、test.comよりはexample.com(個人が所有していない)のほうが良さそう

**Comment by wkmkymt** [comment]
本番環境ではちゃんと用意しといた方がよさそ
