### ISSUE TITLE
広告登録フォームへのアクセス制限or申請後に本許可を実施するまで非有効

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#158]
2つほど選択肢があると考えられる。

1. staffもしくはadminのみアクセス可能にする
staffだと自由度高くて他店舗でも楽そうだが、操作ミスが面倒。
いたずらはないとしても、それを防ぐ手立てはない。
adminのみが妥当なのか？

2. adminユーザ(これもstaffに許可するかは要検討)が広告申請後に、本許可を与えるまでは非表示となり、本許可を出した場合にdisplayに表示されるようになる。

現段階では不特定多数から受けるというよりは、現段階ではstaffが企業にアナログ的に営業仕掛けるのがメインだと思われるので、1でも十分な気がしなくもない。

いずれにせよ一旦1を実装すれば運用に支障なし。

**Comment by wkmkymt** [comment]
あ、そういう感じなの
なら別に`email`も必要なかった感が

1でstaffもアクセス可能にするのが良さそう

**Comment by e45395** [comment]
たしかになくても機能はするんやけど、
広告掲示者の責任元の明示、もしくは2に対応したくなった時に`email`あった方が良いかな。
1スタイルwith Staffで行くなら責任元の連絡先ということで登録をしたstaffのメアド載せる方針も良いかも。

**Comment by e45395** [comment]
将来的なことを考えると2スタイルへの移行も準備しておいた方が良さそうやし、とりあえず`email`残す方針でどうでしょう？

**Comment by wkmkymt** [comment]
広告掲示者の責任元の明示って意味だと逆に`email`だけじゃ足りない気がするし、掲示者テーブルを作るのもアリやったかも

とりあえずDB周りは現状のままでアクセス制御だけ実装しようか

**Comment by e45395** [comment]
アクセス、オナシャス！
adminでも入れるようにね
