### ISSUE TITLE
広告の画像が表示されない

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#178]
真っ暗になる。

スポンサー名やQRコードは問題なし。
htmlに背景画像も指定されており、パスを確認すると画像が返ってきている

**Comment by wkmkymt** [comment]
真っ暗になるタイミングは？

手元ではK-Display表示時もチェックイン/アウト後も表示されてる

**Comment by e45395** [comment]
初期からずっと真っ暗だね。
更新してもチェックイン入れても変わらず真っ暗。

**Comment by e45395** [comment]
PR見た時は大丈夫やったから謎だ…

**Comment by e45395** [comment]
Chrome => 真っ暗
Safari => OK

Chromeで開発してたのにェ…

**Comment by e45395** [comment]
ブラウザ再起動も効果なし

**Comment by wkmkymt** [comment]
Win10/Chromeで正常に表示されてる

ディベロッパツールでスタイル弄って原因わからない？

**Comment by e45395** [comment]
issue建てる前に色々試したんやが、不明やな…
background-colorは反応するけど、imageが無反応

**Comment by e45395** [comment]
![スクリーンショット 2020-05-12 1 28 43](https://user-images.githubusercontent.com/12541987/81586033-f380e900-93ef-11ea-855c-1e0d7e758ea2.png)

**Comment by wkmkymt** [comment]
コンソールにエラー出てるのは関係なさそう？

**Comment by e45395** [comment]
> コンソールにエラー出てるのは関係なさそう？

正解！！！！！！！！
ありがとう！！

adBlockに引っかかってたみたい。背景画像のパス名変えたからかな？

**Comment by wkmkymt** [comment]
やったぜ
