### ISSUE TITLE
SNS認証の仕様再考

### ISSUE THREAD

**Issue by wkmkymt** [wkmkymt/KatharsisDisplay#183]
## 現状

- 同じメールアドレスは全て紐付けられる
  + SNSで新規認証時、既にメールアドレスを用いてアカウントが作成されている場合、そのアカウントとして紐付けられる
    - つまり、最大4つ (メールアドレス・SNS3つ) の方法で同アカウントにログイン可能
  + SNSに登録されているメールアドレスが強制的に用いられる

- SNSでアカウント作成時はランダムなパスワードが仮登録される
  + SNSでログイン時はパスワード不要
  + 登録されたメールアドレスでログインする場合はパスワード必要

### メールアドレスについて

- SNSに捨てアドが登録されている場合でも強制的に登録される
  + 既存のアカウントと紐付けることが不可能
  +  メールが認証されない

### パスワードについて

- SNSでアカウント作成した場合、現在のパスワードがランダムなためパスワード変更 (設定) が不可能

**Comment by e45395** [comment]
> メールアドレスについて

メールアドレスについては大きな問題はならなさそう。
SNSのメアドが捨てアドでも後からプロフ編集でメアド変更はできるし。

> パスワードについて
これはちと問題かもしれない。
が、SNS認証した場合は、SNS認証でしかログインできないサービスとかもあるので何とかはなる。
できれば、SNS経由時専用の/edit/ページを作って、初回ログイン時にパスワードを強制的に変更させるのが理想的か。
sns経由の判別ができるかが問題だが。

込み入った話になりそうなら、また通話で議論しよう。

**Comment by e45395** [comment]
パスワード変更画面から「現在のパスワード」を省くというアイデアはどう？
PRに書いたコメントの問題をクリアできるなら、この方法でも良さそう。

サインインできている時点で、パスワードを再度求める必要はなさそうやし、プロフ編集画面でパスワードを変更していた頃は現在のパスワードを求めていなかった

**Comment by wkmkymt** [comment]
また通話でやろう
