### ISSUE TITLE
リダイレクトを活用して広告QRが読み込まれた際にデータ収集

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#189]
読み込まれた回数や、(サインインしていれば)誰がいつ読み込んだがわかる。

`/adredirect/[ad_id]`にアクセスするとデータを収集+広告に登録されていたURLにリダイレクトする

**Comment by wkmkymt** [comment]
収集するデータは

- ユーザID
- アクセス日時

のみでおｋ？

**Comment by e45395** [comment]
おｋです！
