### ISSUE TITLE
/displays/でショートカットキー押すと全画面表示に

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#231]
ボタンを押すと全画面表示にできるサイトはあるのでJSで対応できそう？

ただ、アクセスしたタイミングだと処理できない可能性はある

**Comment by wkmkymt** [comment]
アクセスしたタイミングは厳しそう

ボタン押したらだと`F11`押すのと変わらんくない？

**Comment by e45395** [comment]
アクセスしたタイミングでできないならあまりメリットないね

**Comment by wkmkymt** [comment]
やっぱり通常はダメみたい
店内のブラウザの設定を弄ればそこだけなら実現できるかもしれないけど
(そこまでしているか？って感じ)

**Comment by e45395** [comment]
余裕があれば、左上部分に半透明拡大アイコン設置して、マウス操作がなければ自動的にアイコンがすぐ消える方式でいこう。

**Comment by e45395** [comment]
ショートカットキー設置するだけで便利そう。実装も楽
