### ISSUE TITLE
スタッフログイン時に全ユーザ情報を表示

### ISSUE THREAD

**Issue by wkmkymt** [wkmkymt/KatharsisDisplay#44]
管理者ユーザでログインした時に各店舗にチェックインしているユーザ情報を一覧表示させる

**Comment by e45395** [comment]
staffユーザでサインインした時に対応店舗にチェックインしているユーザ一覧を表示するように仕様を変更

**Comment by wkmkymt** [comment]
ユーザ一覧 -> ユーザページ -> チェックアウトボタン -> 確認ダイアログ -> 実行
