### ISSUE TITLE
SNS連携認証

### ISSUE THREAD

**Issue by wkmkymt** [wkmkymt/KatharsisDisplay#78]
- Twitter / Facebook等によるアカウント作成

**Comment by e45395** [comment]
https://qiita.com/nakanishi03/items/2dfe8b8431a044a01bc6

各種SNSのアカウント必要

**Comment by e45395** [comment]
ツイッター認証でサインアップからのサインインできたはずやけど、再度サインアウトしてサインインしたらエラー吐いた
![image](https://user-images.githubusercontent.com/12541987/81087367-9939e100-8f34-11ea-8129-7fbe02dd5664.png)
