### ISSUE TITLE
K-Displayに広告を表示できるようにする

### ISSUE THREAD

**Issue by e45395** [wkmkymt/KatharsisDisplay#99]
ユーザの間に良い感じに広告を挿入したい

**Comment by e45395** [comment]
広告の要素
・提示者(自由入力でも十分やと思われるが、提示者モデルとテーブルを用意したほうが検索などが容易？しかし、検索をかけるほど大量の広告データを蓄積することが発生するのか、蓄積する意味はあるのかの問題あり)
・画像(これが広告本体になりそう)
・掲載店舗(複数)
・表示期間の指定(いつからいつまで)
・URL、もしくはそれをQRコード化したもの(実用面ではQRコードのみを表示する)

**Comment by wkmkymt** [comment]
表示期間の指定は店舗ごと？同一？

**Comment by e45395** [comment]
同一でいこう

**Comment by e45395** [comment]
表示アルゴリズム:
表示されるユーザ数: n 、表示される広告数: mとする。
(mは別途nに合わせてアルゴリズム立てて決定するのも手。ひとまずは掲載期間以内のは全て表示(?))
できれば、(n>1or2であるとき) n >= mが理想的

if(n!=0 and m!=0)
  if max(n >= m)
    [n / m]人のユーザの表示後に広告を1つずつ挿入
  else 
    ユーザを1人表示後に[m / n]個の広告の挿入
else
  n or mを片っ端から表示

**Comment by wkmkymt** [comment]
テーブル案
あと掲載期間終了後残すかどうか、どうしよ

### Advertisement

| *Column* | *Type* |
| --- | --- |
| id | bigint |
| sponsor | string |
| adimg | binary |
| url | string |
| start_date | date |
| end_date | date |

### AdContract

| *Column* | *Type* |
| --- | --- |
| id | bigint |
| advertisement_id | bigint |
| shop_id | bigint |

**Comment by e45395** [comment]
掲載期間終わってもログとして残す仕様でいこう

**Comment by wkmkymt** [comment]
表示順のルール守りつつリアルタイム更新するのむずない？

**Comment by e45395** [comment]
難しそうなら、ユーザ全員=>広告全部って感じでも良いかもしれない

**Comment by wkmkymt** [comment]
リアルタイム諦めて一定時間リロードならいけるけどどうしよ

**Comment by e45395** [comment]
順序よりリアルタイム制取りたさあるな。
広告がなかったり少なかったりすることも往々にしてありそうやし

**Comment by wkmkymt** [comment]
今更やけどフォームから投稿させるなら連絡先が必要やな
広告テーブルに`email`追加するか広告主テーブル作るか？

**Comment by e45395** [comment]
現状のテーブルにsponsorがstringになってるし、email追加だけでOKかな？
